### ISSUE TITLE
Make ajax calls use mw.ajaxBeforeSend

### ISSUE THREAD

**Issue by tperrier** [tperrier/mwachx#119]
We could potentially make this global so that it loads on all pages regardless of if that page uses ajax or not.

**Comment by bderenzi** [comment]
I think we should definitely make it load globally

**Comment by tperrier** [comment]
Yes, I'm going to need it for the facility dropdown select if a user 
is_staff.  Should be easy to do.  We can add an onload function to the 
the mwach.js file.
