### ISSUE TITLE
Should the global tooltip call happen every page regardless?

### ISSUE THREAD

**Issue by bderenzi** [tperrier/mwachx#121]
```
{% block js_onLoad %}
{% comment %} <script> /*for syntax highlighting*/ {% endcomment %} 
   mw.tooltips();
{% comment %} </script> {% endcomment %} 
{% endblock %}
```

**Comment by tperrier** [comment]
Yes, we can put that in the mwach.js onload function as well.

Sometimes it might need to be called in a Modal's show function as 
well.  The datepicker one will need be called from the visit attended modal.
