### ISSUE TITLE
[calls] Record phone call happened, with result

### ISSUE THREAD

**Issue by bderenzi** [tperrier/mwachx#17]

**Comment by tperrier** [comment]
Make button group with send button and pop up modal

**Comment by bderenzi** [comment]
Just to confirm: this is going on the "find a user" contact list page, correct? Or are you talking about building out all of the /calls/ feature by tomorrow?

**Comment by tperrier** [comment]
Yes, I was imagining just another button on the find user page.  It can be
a stub right now that doesn't do anything with the database.

**Comment by bderenzi** [comment]
This is done from the sense that the button exists. Leaving it open though as a reminder to implement some backend. Moving it out of training milestone because of that

**Comment by tperrier** [comment]
Possible Results of a phone call: ringing no answer, no ring, answered.

We used to have a duration field, but I don't think this is important.

**Comment by tperrier** [comment]
I'm closing this.  Seems like we're removing that button on the participants search list and adding this functionality else where.

**Comment by bderenzi** [comment]
Meant to say I had closed #9
