### ISSUE TITLE
For book visits, we are getting repeats for people

### ISSUE THREAD

**Issue by bderenzi** [tperrier/mwachx#187]

**Comment by tperrier** [comment]
I'm trying to reproduce this and can't right now.  I am using the visit from Regina in Bondo.  I skiped it enought times to move it from daily checks to book checks.  Then I skipped it twice in book checks.  No duplicats were made.

We need to figure out the exact steps to reproduce this.  Does it only do this on Openshift? If so could it be an ajax problem?

**Comment by tperrier** [comment]
I just did this for two more participants.  At least running on localhost I can't replicate? Very strange.

That said, I still don't like the way the visits work.  Creating multiple copies of a visit for missed visits makes the code very complicated to understand (and the visit admin database hard to debug).

I think we should have a new Model called missed visit that records all the missed visits and book checks. (but I think it's low priority - unless we can replicate this bug)

**Comment by bderenzi** [comment]
Can you reproduce the bug on openshift?

**Comment by tperrier** [comment]
Nope. I can't reproduce this bug.  If I see it I'll record exactly what 
happened.  All I remember doing during the Tuesday meeting was clicking 
on skip and multiple copies appeared in the book check.
