### ISSUE TITLE
Openshift KEEP_DB is not working

### ISSUE THREAD

**Issue by tperrier** [tperrier/mwachx#188]

**Comment by tperrier** [comment]
closed from ca7d369

**Comment by tperrier** [comment]
This seems to be broken still.

**Comment by bderenzi** [comment]
Do we need it? Why don't we just make it not reset_db on push, then we can rhc shell in and call the reset if we want to

**Comment by tperrier** [comment]
closed in dc3bbe1  
reset_db manually from now on.
