### ISSUE TITLE
Remove feature: Dismissing a pending message goes back to new message queue

### ISSUE THREAD

**Issue by bderenzi** [tperrier/mwachx#220]
This is a bit annoying. An alternative is that if they came from the pending message queue then they go back, but if they don't it's very jarring and confusing. I think we can either remove it completely (my preference) or make it depend on the referring page

**Comment by tperrier** [comment]
Sure, make it depend on coming from the pending message queue. Though, I 
have to question if coming not from the pending message queue is just an 
artifact of training.  My guess is 98% of the time they will come from 
the pending queue.

**Comment by bderenzi** [comment]
I think this might come up during enrollment. But good point we will see it
a lot during training. Should reply also redirect?

**Comment by tperrier** [comment]
Here's the bigger issue, and it makes me think we should just remove 
this feature.

What do we do if there are multiple pending messages for a participant?  
Say someone sends three messages during the night (not 
uncommon/unexpected).  Two of them will be dismissed and one replied 
to.  The workflow needs to stay on the same page in this case.

So the idea thing to do is go back to the Message queue if we have just 
come from there, but only if there are no other pending messages for 
that participant. We then need to write tests that if we accidentally 
break anything in that pipeline we know if it happens.

**Comment by bderenzi** [comment]
Not implemented (so, fixed) in angular-integration branch
