### ISSUE TITLE
drf and angular: seems like a good idea

### ISSUE THREAD

**Issue by tperrier** [tperrier/mwachx#224]
When we have time it would be great to implement this. It would simplify making an android app in the future.

http://blog.kevinastone.com/getting-started-with-django-rest-framework-and-angularjs.html

**Comment by bderenzi** [comment]
This video was useful: https://www.youtube.com/watch?v=vWJorwEQWLk

And here's the repo: https://github.com/nnja/tweeter/tree/master/tweeter
