### ISSUE TITLE
Go figure out this billing stuff with Africa's Talking

### ISSUE THREAD

**Issue by bderenzi** [tperrier/mwachx#228]
What we need:
- Monitor our account for us. Do not let it go empty. What do you need, a deposit?
- API to monitor our account in an automated fashion 
- Invoice ahead of time OR a receipt

**Comment by tperrier** [comment]
There is an option in the Africa's Talking interface for Billing Notifications.  However, I can't figure out what the email account associated witht the account is.  Right now the billing notification is set to 0.05 USD.  I think we should put it at $1 (that is 90 messages).

**Comment by bderenzi** [comment]
Ok, I will ask them about the email. Do we have an email we would like
associated with the account? Might be good to have it go to some group
account or mailing list or something. Would be good if everyone saw it

**Comment by tperrier** [comment]
I assume the email would go to my account since that's what is registered
with our Africa's Talking Account.  However, I couldn't find a place to
change this email (or even where it was listed).

Once we get our first low reminder notification I can just set up a forward
filter in my gmail.

**Comment by bderenzi** [comment]
Maybe we can set the threshold to $24.50 or something really high just to
test the low-balance notification?
