### ISSUE TITLE
Initial welcome text 'congrats' and 'five letter'

### ISSUE THREAD

**Issue by bderenzi** [tperrier/mwachx#231]
Two changes:
- Matemo really wants it to say "congratulations". I don't care
- It current says your "5 letter verification code". We should change to "5 digit"

**Comment by tperrier** [comment]
The message is going to be coming from the official translated set. With
are going to be vetted by the entire team. Changing it here has no effect
on the final swahilia welcome message. Of course it takes 20 sec to do this
and make him happy.
