### ISSUE TITLE
[mathare] Upcoming visits page

### ISSUE THREAD

**Issue by bderenzi** [tperrier/mwachx#265]
they want to see visits coming up tomorrow at least so they can plan a bit.

**Comment by bderenzi** [comment]
All sites requested this feature. They are asking for a week in advance. Big motivation seems to be planning leave: they want to make sure they're not taking off when there is a lot of work to do

**Comment by tperrier** [comment]
I think this feature makes a lot of sense and I can see the need.  I think
this should be a separate page from the current visit Pending page.  The
idea behind the visit pending page is that you check it every day and
remove all visits from that page.  If this page is also showing up coming
visits for the next few weeks then it doesn't make sense to clear them
everyday.

I think that if there was a button on the Visit Pending that linked to the
upcoming visits that would work.

**Comment by bderenzi** [comment]
Yes. There is actually already a button for this on the main page lower right called "upcoming visits". Can also add one to the visits page
