### ISSUE TITLE
current date (in orange) does not update as you use the forward-in-time button

### ISSUE THREAD

**Issue by bderenzi** [tperrier/mwachx#289]

**Comment by tperrier** [comment]
Is this the one in the top right corner? It moves in both directions for me? This might be a timezone issue.  I struggled to make it work for me and had to force a date conversion through UCT - maybe if you are in the Eastern Hemisphere it still doesn't work.

**Comment by bderenzi** [comment]
Yes. It stayed at oct 20 even though I was 40+ days in the future
