### ISSUE TITLE
[visits] DEBUG Remove default value for 'next visit'

### ISSUE THREAD

**Issue by bderenzi** [tperrier/mwachx#39]
It is currently set to one_week for testing purposes.

**Comment by tperrier** [comment]
this might be done? but I don't know what it means.

**Comment by bderenzi** [comment]
In `add-new-visit-modal.html` we set a default date of +1 week for the 'next visit': `data-date='{{ONE_WEEK|date:"Y-m-d"}}'`.

Probably we shouldn't do that, but for testing I didn't want to open the date picker
