### ISSUE TITLE
Add translate and prompted dropdowns to message

### ISSUE THREAD

**Issue by tperrier** [tperrier/mwachx#44]
Just stub these for now.  Add the functionality later.

**Comment by tperrier** [comment]
We need to make ajax call backs to make these persistant.

**Comment by tperrier** [comment]
@bderenzi took care of a lot of this.  Other open issues deal with remaining parts.

**Comment by bderenzi** [comment]
Thanks for catching stuff I forgot to close. Left this guy open on purpose because the functionality isn't implemented yet--just the UI

**Comment by bderenzi** [comment]
You're right, this issue doesn't make sense anymore
