### ISSUE TITLE
[contact] Review the style for the single contact page

### ISSUE THREAD

**Issue by bderenzi** [tperrier/mwachx#49]

**Comment by tperrier** [comment]
The full page UI was not working on small computers.  The message column is only supposed to be as high as the screen-height, however, on small screens it was flowing down.  This made it very hard to navigate. 

Now that we have gotten rid of the footer I think the site CSS can be redone to fix this.

**Comment by bderenzi** [comment]
Not sure I follow exactly where the issue is, but can you check the resolution of the computers we will be using for the actual study before you go? It would be good to know the resolution we have to work with for the final product.

To check: 
1. Open Chrome
2. Go to any web page
3. Open developer tools (ctl shift J should work)
4. Resize the window to be full size. 
5. During the resize, the resolution should pop up in the upper right corner.

That way we know we're testing at the same resolution as our users are using.
