### ISSUE TITLE
Change Html5DateInput to be dd-mm-yyyy instead of mm-dd-yyyy

### ISSUE THREAD

**Issue by tperrier** [tperrier/mwachx#50]

**Comment by bderenzi** [comment]
This is controlled by the browser and based on the system settings. See:
http://stackoverflow.com/questions/7372038/is-there-any-way-to-change-input-type-date-format

If you change system settings away from US, it should work. The other option is to not use html 5 and use a custom widget like the jquery one:
http://api.jqueryui.com/datepicker/

**Comment by tperrier** [comment]
There are a few things I didn't like about the HTML5 date picker.  It's a
quick and easy way to get a nice date dialog but we need to find a UI addon
for forms inputs that we like (I'd like one with customized drop downs as
well).

jQueryUI is heavy but if there are other things we want to use in it then I
would go with it.

Fuel UX also looks nice: http://getfuelux.com/javascript.html#datepicker

**Comment by bderenzi** [comment]
Ok, fuel UX looks good to me. I'm going to close this and split it into a couple different tasks.
