### ISSUE TITLE
[test] Explain Djano test system to brian

### ISSUE THREAD

**Issue by bderenzi** [tperrier/mwachx#60]

**Comment by tperrier** [comment]
I've only used tests once or twice in Django

The last modulo of of the Django tutorial
https://docs.djangoproject.com/en/1.7/intro/tutorial05/ is about
testing.  I've read through it a few times and done basic stuff.  I've also
heard django-nose https://github.com/django-nose/django-nose is nice.

I'll go over these with you sometime.
