### ISSUE TITLE
[UX] Rename Contact to Participant 

### ISSUE THREAD

**Issue by tperrier** [tperrier/mwachx#61]
Jennifer wants Contacts called Participant.  We could refactor all the models/code to rename them there but I think we just keep contact in the code and participant in the UI.

**Comment by bderenzi** [comment]
I sort of like the idea of refactoring everything, but agreed that might not be the top priority right now.

**Comment by tperrier** [comment]
It's just a bug hunt.  Find/Silver Search (ag) might work for basic
replacement but this is complicated.  I think I'd start with UX only and
then later do the underling models.
