### ISSUE TITLE
[IMPORTANT] Get the final screen dimensions we should develop for

### ISSUE THREAD

**Issue by bderenzi** [tperrier/mwachx#71]
1350 x 320 is a ridiculous resolution. How can it really be that short??

Brian

**Comment by tperrier** [comment]
I'm going to move this to @bderenzi to do at training.  If you have the time you might want to meet Dyphna for lunch and could get this information sooner.  I didn't play around with the OS screen resolution - but I remember Chrome was showing me 1350 x 320.

**Comment by bderenzi** [comment]
Ok, confirmed that the small laptop was running 1356 x 629. Let's call that 1350 x 600 to be safe.

I think the reason that @tperrier saw 1350 x 320 is because if the developer tools console is in the same window it shrinks the viewport. Have to pop it out to get the real one.

It is worth noting that the Mathare crowd really wants to be using the 7-inch tablets instead of the laptop for ongoing messaging. Enrollment will still likely be laptop-based.

**Comment by tperrier** [comment]
Still super small, but 629 is better than 320.  Thanks for checking into
this.
