### ISSUE TITLE
[participant] Remove 'prompted' field 

### ISSUE THREAD

**Issue by bderenzi** [tperrier/mwachx#92]

**Comment by tperrier** [comment]
Yes, prompted does not need to be on each individual message.

The way I see it prompted will be temporal - any response from a 
participant that comes in less than 36h after an outgoing message to 
them.  We can calculated this automatically - I think we should leave 
the field on the Message object in the models though.

Related might be renamed "Relevant" and has to do with the content of 
the message.  If the message content is related to one of the last 
outgoing messages then the message should be marked as relevant.

I think with these two fields we will have a lot better understanding of 
the messages coming in.
